
// Internal representation of a Phaser packfile.
export interface PackFile {
    meta: PackFileMetadata;
    [key: string]: PackFileSection | PackFileFiles | PackFileMetadata;
}

export interface PackFileSection {
    [key: string]: PackFileSection | PackFileFiles;
}

// Pack file metadata (generated by our app or Phaser Editor)
export interface PackFileMetadata {
    generated: string;
    app: string;
    url: string;
    version: string;
    copyright: string;
}

export type PackFileFileType = 'animation' | 'atlas' | 'atlasXML' | 'audio' |
    'audioSprite' | 'binary' | 'bitmapFont' | 'glsl' | 'html' | 'htmlTexture' |
    'image' | 'json' | 'multiatlas' | 'pack' | 'plugin' | 'scenePlugin' |
    'script' | 'spritesheet' | 'svg' | 'text' | 'tilemapCSV' | 'tilemapImpact' |
    'tilemapTiledJSON' | 'unityAtlas' | 'xml';

export interface PackFileFiles {
    prefix?: string;
    path?: string;
    defaultType?: PackFileFileType;
    files: PackFileFile[];
}

export interface PackFileFile {
    type?: PackFileFileType;
    key: string;
    url?: string;
    extension?: string;
}